name: Credit Card Transactions CICD

on:
  push:
    branches:
      - main

jobs:
  deploy-to-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Upload PySpark Job to GCS
      - name: Upload Spark Job to GCS
        run: |
          gsutil cp spark_job.py gs://credit-card-data-analysis/spark_job/

      # Upload Airflow DAG to Composer
      - name: Upload Airflow DAG to Composer
        run: |
          gcloud composer environments storage dags import \
            --environment airflow-cluster \
            --location us-central1 \
            --source airflow_job.py